### ISSUE TITLE
Nothing happens after completing the readme

### ISSUE THREAD

**Issue by Zaydene** [michaelwnelson/reddit-modqueue-discord#1]
I followed the readme exactly as it's written, but after setting up the heroku website, it's not clear what else there is to do. I tried manually deploying which did not appear to give any errors, but also did not seem to work. I'd report a thread, I'd verify it was in the modqueue, but would not receive any message.

Admittedly I'm ignorant when it comes to all of this, but I don't believe I overlooked anything. Is this still working, or did I miss something during setup that may not be super obvious to a layperson?

**Comment by michaelwnelson** [comment]
I wonder if I forgot to include ensuring your Dyno was *configured and enabled*.

If you navigate to the **Overview** tab on your Heroku dashboard, do you see anything listed under **Dyno formation**? You should see something along the lines of:
```
worker   python bot.py                 ON
```

**Here's a screenshot:**
![Screenshot of Dyno formation on the Heroku dashboard](https://user-images.githubusercontent.com/1460034/87894694-18559600-ca09-11ea-9674-69f76269327f.png)


If it's `OFF` or you don't see it listed, click on the **Configure Dynos** link, click the **Edit** button (pencil) and ensure it's toggled on.

**Here's a screenshot:**
![Screenshot of enabling a free dyno](https://user-images.githubusercontent.com/1460034/87894718-299ea280-ca09-11ea-937d-4ee51b9bdab3.png)

Hopefully that helps! If not let me know and we can debug further.

**Comment by Zaydene** [comment]
That was it, thank you so much! Would be great to include those instructions in the readme!

A few things to ask/note if you don't mind:

The oauth link you provided is broken because the lack of https, the correct one is now: https://not-an-aardvark.github.io/reddit-oauth-helper/

After setting it up again (I deleted it after my failed attempt earlier), I only tried providing the moderator-oriented permissions from the above and it did not seem to work. But when I made a new token with all permissions it worked. Is it absolutely necessary to have access to all perms?

~~Am I able to delete the 'developed applications' app that was used to generate the token? I understand I need to keep authorized application intact. https://i.imgur.com/scFvN2T.png~~ - Edit: Yes you need to keep both entries 🙂

Is there a limit from Heroku that you know of as a free user? Example being maybe only able to run this script 100 times a months before having to upgrade the account? Maybe it only runs every x minutes, or is it realtime?

Am I able to somehow run this completely off a local machine? I'm not looking for a complete walk-through if it's possible, maybe the name of a program that replaces the service that Heroku provides?

**Comment by michaelwnelson** [comment]
Glad that worked, I'll definitely add those details to the README!

>Is there a limit from Heroku that you know of as a free user? Example being maybe only able to run this script 100 times a months before having to upgrade the account? Maybe it only runs every x minutes, or is it realtime?

Refer to the details on the [Free dyno hour pool](https://devcenter.heroku.com/articles/free-dyno-hours#free-dyno-hour-pool). I'll quote it here for convenience and **bold** the important part:

>Personal accounts are given a base of 550 free dyno hours each month. In addition to these base hours, accounts which verify with a credit card will receive an additional 450 hours added to the monthly free dyno quota. **This means you can receive a total of 1000 free dyno hours per month, if you verify your account with a credit card.**

Even in the longest months, 31 days, that's only 744 hours. So, as long as you add a credit card (which won't be charge) you'll be able to run the dyno for free indefinitely with the 1000 free hours.

> Am I able to somehow run this completely off a local machine? I'm not looking for a complete walk-through if it's possible, maybe the name of a program that replaces the service that Heroku provides?

You definitely can! Unfortunately, it won't be an easy self-service install to just _replace_ what Heroku provides. Heroku provides a server that runs and interprets [Python](https://www.python.org/) and also hosts a [PostgreSQL](https://www.postgresql.org/) database. You would have to learn and get comfortable with installing and supporting both Python and PostgreSQL on your system to run this locally. Further you'd probably want to create a service that ensures the script is up and starts with your system after a reboot.
